services:
  react-frontend:
    container_name: react-frontend
    build: ../New-Stadex-React 
    ports:
      - "3000:3000"
    volumes:
      - "../New-Stadex-React:/app"
      - "/app/node_modules"

  php-symfony:
    container_name: php-symfony
    build:
      context: ./.docker/php-symfony
    depends_on:
      - postgres
    links:
      - postgres
    tty: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www/stadex-symfony
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: